trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self

- task: AzureCLI@2
  displayName: 'Test Azure Login'
  inputs:
    azureSubscription: 'Azure-ServiceConnection'
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      az account show
