trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  workingDirectory: 'terraform'
  TF_IN_AUTOMATION: 'true'
  TF_INPUT: 'false'

steps:

# Checkout source
- checkout: self

# Install Terraform
- task: TerraformInstaller@1
  displayName: 'Install Terraform'
  inputs:
    terraformVersion: 'latest'

# Terraform Init
- task: AzureCLI@2
  displayName: 'Terraform Init'
  inputs:
    azureSubscription: 'Azure-ServiceConnection'
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      cd $(workingDirectory)

      rm -rf .terraform

      terraform init \
        -reconfigure \
        -backend-config="backend-dev.hcl"
  env:
    TF_IN_AUTOMATION: $(TF_IN_AUTOMATION)
    TF_INPUT: $(TF_INPUT)
    TF_VAR_admin_password: $(TF_VAR_admin_password)

# Terraform Format Check
- task: AzureCLI@2
  displayName: 'Terraform Format Check'
  inputs:
    azureSubscription: 'Azure-ServiceConnection'
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      cd $(workingDirectory)

      terraform fmt -check
  env:
    TF_IN_AUTOMATION: $(TF_IN_AUTOMATION)
    TF_INPUT: $(TF_INPUT)
    TF_VAR_admin_password: $(TF_VAR_admin_password)

# Terraform Validate
- task: AzureCLI@2
  displayName: 'Terraform Validate'
  inputs:
    azureSubscription: 'Azure-ServiceConnection'
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      cd $(workingDirectory)

      terraform validate
  env:
    TF_IN_AUTOMATION: $(TF_IN_AUTOMATION)
    TF_INPUT: $(TF_INPUT)
    TF_VAR_admin_password: $(TF_VAR_admin_password)

# Terraform Plan
- task: AzureCLI@2
  displayName: 'Terraform Plan'
  inputs:
    azureSubscription: 'Azure-ServiceConnection'
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      cd $(workingDirectory)

      terraform plan \
        -lock-timeout=5m \
        -input=false \
        -var-file="./environments/dev.tfvars"
  env:
    TF_IN_AUTOMATION: $(TF_IN_AUTOMATION)
    TF_INPUT: $(TF_INPUT)
    TF_VAR_admin_password: $(TF_VAR_admin_password)