trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  workingDirectory: terraform

steps:
- checkout: self

- task: TerraformInstaller@1
  displayName: Install Terraform
  inputs:
    terraformVersion: latest

- task: AzureCLI@2
  displayName: Terraform Validate
  inputs:
    azureSubscription: 'Azure-ServiceConnection'
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      cd $(workingDirectory)

      terraform init

      terraform validate
